package eu.datex.statefulpush;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-11-24T15:17:29.865+01:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "statefulPushService",
                  wsdlLocation = "file:/Users/mauricereigman/workspaces/NDW/NCIS-CloudNative/DatexII/src/main/resources/xsd/StatefulPush.wsdl",
                  targetNamespace = "http://datex2.eu/wsdl/statefulPush/2020")
public class StatefulPushService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://datex2.eu/wsdl/statefulPush/2020", "statefulPushService");
    public final static QName StatefulPushSoapEndPoint = new QName("http://datex2.eu/wsdl/statefulPush/2020", "statefulPushSoapEndPoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/mauricereigman/workspaces/NDW/NCIS-CloudNative/DatexII/src/main/resources/xsd/StatefulPush.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StatefulPushService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/mauricereigman/workspaces/NDW/NCIS-CloudNative/DatexII/src/main/resources/xsd/StatefulPush.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StatefulPushService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StatefulPushService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatefulPushService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StatefulPushService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StatefulPushService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StatefulPushService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StateFulPushInterface
     */
    @WebEndpoint(name = "statefulPushSoapEndPoint")
    public StateFulPushInterface getStatefulPushSoapEndPoint() {
        return super.getPort(StatefulPushSoapEndPoint, StateFulPushInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StateFulPushInterface
     */
    @WebEndpoint(name = "statefulPushSoapEndPoint")
    public StateFulPushInterface getStatefulPushSoapEndPoint(WebServiceFeature... features) {
        return super.getPort(StatefulPushSoapEndPoint, StateFulPushInterface.class, features);
    }

}
