package eu.datex.statefulpush;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-11-24T15:17:29.823+01:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://datex2.eu/wsdl/statefulPush/2020", name = "stateFulPushInterface")
@XmlSeeAlso({eu.datex.energyinfrastructure.ObjectFactory.class, eu.datex.messagecontainer.ObjectFactory.class, eu.datex.commonextension.ObjectFactory.class, eu.datex.locationreferencing.ObjectFactory.class, eu.datex.locationextension.ObjectFactory.class, eu.datex.facilities.ObjectFactory.class, eu.datex.informationmanagement.ObjectFactory.class, eu.datex.common.ObjectFactory.class, eu.datex.exchangeinformation.ObjectFactory.class, eu.datex.d2payload.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StateFulPushInterface {

    @WebMethod(action = "http://datex2.eu/wsdl/statefulPush/2020/openSession")
    @WebResult(name = "openSessionOutput", targetNamespace = "http://datex2.eu/wsdl/statefulPush/2020", partName = "return")
    public eu.datex.exchangeinformation.ExchangeInformation openSession(

        @WebParam(partName = "body", name = "openSessionInput", targetNamespace = "http://datex2.eu/wsdl/statefulPush/2020")
        eu.datex.exchangeinformation.ExchangeInformation body
    );

    @WebMethod(action = "http://datex2.eu/wsdl/statefulPush/2020/putData")
    @WebResult(name = "putDataOutput", targetNamespace = "http://datex2.eu/wsdl/statefulPush/2020", partName = "return")
    public eu.datex.exchangeinformation.ExchangeInformation putData(

        @WebParam(partName = "body", name = "putDataInput", targetNamespace = "http://datex2.eu/wsdl/statefulPush/2020")
        eu.datex.messagecontainer.MessageContainer body
    );

    @WebMethod(action = "http://datex2.eu/wsdl/statefulPush/2020/closeSession")
    @WebResult(name = "closeSessionOutput", targetNamespace = "http://datex2.eu/wsdl/statefulPush/2020", partName = "return")
    public eu.datex.exchangeinformation.ExchangeInformation closeSession(

        @WebParam(partName = "body", name = "closeSessionInput", targetNamespace = "http://datex2.eu/wsdl/statefulPush/2020")
        eu.datex.exchangeinformation.ExchangeInformation body
    );

    @WebMethod(action = "http://datex2.eu/wsdl/statefulPush/2020/keepAlive")
    @WebResult(name = "keepAliveOutput", targetNamespace = "http://datex2.eu/wsdl/statefulPush/2020", partName = "return")
    public eu.datex.exchangeinformation.ExchangeInformation keepAlive(

        @WebParam(partName = "body", name = "keepAliveInput", targetNamespace = "http://datex2.eu/wsdl/statefulPush/2020")
        eu.datex.exchangeinformation.ExchangeInformation body
    );

    @WebMethod(action = "http://datex2.eu/wsdl/statefulPush/2020/putSnapshotData")
    @WebResult(name = "putSnapshotDataOutput", targetNamespace = "http://datex2.eu/wsdl/statefulPush/2020", partName = "return")
    public eu.datex.exchangeinformation.ExchangeInformation putSnapshotData(

        @WebParam(partName = "body", name = "putSnapshotDataInput", targetNamespace = "http://datex2.eu/wsdl/statefulPush/2020")
        eu.datex.messagecontainer.MessageContainer body
    );
}
