/*
 * roaming-location-prd
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ocpi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import ocpi.model.ExceptionalPeriod;
import ocpi.model.RegularHours;
/**
 * OcpiHours
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-31T14:42:19.145134152+02:00[Europe/Amsterdam]")
public class OcpiHours {
  @JsonProperty("twentyfourseven")
  private Boolean twentyfourseven = null;

  @JsonProperty("regular_hours")
  private List<RegularHours> regularHours = null;

  @JsonProperty("exceptional_openings")
  private List<ExceptionalPeriod> exceptionalOpenings = null;

  @JsonProperty("exceptional_closings")
  private List<ExceptionalPeriod> exceptionalClosings = null;

  public OcpiHours twentyfourseven(Boolean twentyfourseven) {
    this.twentyfourseven = twentyfourseven;
    return this;
  }

   /**
   * Get twentyfourseven
   * @return twentyfourseven
  **/
  @Schema(description = "")
  public Boolean isTwentyfourseven() {
    return twentyfourseven;
  }

  public void setTwentyfourseven(Boolean twentyfourseven) {
    this.twentyfourseven = twentyfourseven;
  }

  public OcpiHours regularHours(List<RegularHours> regularHours) {
    this.regularHours = regularHours;
    return this;
  }

  public OcpiHours addRegularHoursItem(RegularHours regularHoursItem) {
    if (this.regularHours == null) {
      this.regularHours = new ArrayList<>();
    }
    this.regularHours.add(regularHoursItem);
    return this;
  }

   /**
   * Get regularHours
   * @return regularHours
  **/
  @Schema(description = "")
  public List<RegularHours> getRegularHours() {
    return regularHours;
  }

  public void setRegularHours(List<RegularHours> regularHours) {
    this.regularHours = regularHours;
  }

  public OcpiHours exceptionalOpenings(List<ExceptionalPeriod> exceptionalOpenings) {
    this.exceptionalOpenings = exceptionalOpenings;
    return this;
  }

  public OcpiHours addExceptionalOpeningsItem(ExceptionalPeriod exceptionalOpeningsItem) {
    if (this.exceptionalOpenings == null) {
      this.exceptionalOpenings = new ArrayList<>();
    }
    this.exceptionalOpenings.add(exceptionalOpeningsItem);
    return this;
  }

   /**
   * Get exceptionalOpenings
   * @return exceptionalOpenings
  **/
  @Schema(description = "")
  public List<ExceptionalPeriod> getExceptionalOpenings() {
    return exceptionalOpenings;
  }

  public void setExceptionalOpenings(List<ExceptionalPeriod> exceptionalOpenings) {
    this.exceptionalOpenings = exceptionalOpenings;
  }

  public OcpiHours exceptionalClosings(List<ExceptionalPeriod> exceptionalClosings) {
    this.exceptionalClosings = exceptionalClosings;
    return this;
  }

  public OcpiHours addExceptionalClosingsItem(ExceptionalPeriod exceptionalClosingsItem) {
    if (this.exceptionalClosings == null) {
      this.exceptionalClosings = new ArrayList<>();
    }
    this.exceptionalClosings.add(exceptionalClosingsItem);
    return this;
  }

   /**
   * Get exceptionalClosings
   * @return exceptionalClosings
  **/
  @Schema(description = "")
  public List<ExceptionalPeriod> getExceptionalClosings() {
    return exceptionalClosings;
  }

  public void setExceptionalClosings(List<ExceptionalPeriod> exceptionalClosings) {
    this.exceptionalClosings = exceptionalClosings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OcpiHours ocpiHours = (OcpiHours) o;
    return Objects.equals(this.twentyfourseven, ocpiHours.twentyfourseven) &&
        Objects.equals(this.regularHours, ocpiHours.regularHours) &&
        Objects.equals(this.exceptionalOpenings, ocpiHours.exceptionalOpenings) &&
        Objects.equals(this.exceptionalClosings, ocpiHours.exceptionalClosings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(twentyfourseven, regularHours, exceptionalOpenings, exceptionalClosings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OcpiHours {\n");
    
    sb.append("    twentyfourseven: ").append(toIndentedString(twentyfourseven)).append("\n");
    sb.append("    regularHours: ").append(toIndentedString(regularHours)).append("\n");
    sb.append("    exceptionalOpenings: ").append(toIndentedString(exceptionalOpenings)).append("\n");
    sb.append("    exceptionalClosings: ").append(toIndentedString(exceptionalClosings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
